server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
spring:
  threads:
    virtual:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:h2:file:./data/receiptsdb"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  application:
    name: kameleon-receipts-reader
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 8MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 500632763514-c9emfbg99m141n6lqndf47md81pnlgn0.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web.cors: DEBUG
    org:
      apache:
        coyote:
          http11: DEBUG
openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPEN_API_KEY}
kameleon:
  redirect:
    url: http://localhost:4200
